name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        env: 
          MINIO_ACCESS_KEY: ${{ secrets.TEST_MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.TEST_MINIO_SECRET_KEY }}
        run: go test ./cmd
        
      - name: Build
        run: go build -o go-k8s-srv ./cmd

      - name: Build Docker Image
        run: docker build .
